# Generated by Django 5.1.2 on 2024-12-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_background',
            field=models.TextField(blank=True, null=True, verbose_name='システム背景'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='システム名'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_summary',
            field=models.TextField(blank=True, null=True, verbose_name='システム概要'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='サムネイル画像'),
        ),
    ]
