# Generated by Django 5.1.2 on 2024-12-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_system_system_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='system_url',
            field=models.URLField(blank=True, null=True, verbose_name='システムURL'),
        ),
    ]
